### ISSUE TITLE
Plugin should mark job as FAILED if upload fails

### ISSUE THREAD

**Issue by nfalco79** [ctron/package-drone-jenkins#1]
The plugin should marks the job as failed if upload fails.

Other way add checkbox settings to customise the behaviour if mark job failed when upload fails or not.

By default should be enabled otherwise you never know if artifact was deployed until you are looking in the channel them.

> Package Drone Server URL: http://10.0.5.203:8080
> ERROR: Failed to upload com.example-1.4.0.v43000018.zip: 401 Unauthorized = Please authenticate
> Finished: SUCCESS

**Comment by ctron** [comment]
Different people have different requirements ;-)

But I would say adding a configuration option which allows to mark the build failed in this case would make sense.

**Comment by nfalco79** [comment]
Thank for the quicly response.

I propose the same default behaviour of similar plugin as the embedded plugin "Archieve the Artifacts", "Deploy artifact to Artifactory/Maven" plugin and all the "Send build artifact over ...." plugins.

**Comment by ctron** [comment]
Well I do have a scenario where I don't want the build to fail. So adding a check box sounds like a good idea.

If you can make a pull request I can do it on Monday.

**Comment by ctron** [comment]
Thanks for the patch! I just release version 0.2.4, which contains your fix. I am not sure though how long it will take until the upload is visible. Last time it was a few days.
