### ISSUE TITLE
Release version 0.5.0

### ISSUE THREAD

**Issue by ctron** [ctron/package-drone-jenkins#26]
Release a new version:
* #24: use credentials plugin
* #25: use proxy settings

**Comment by nfalco79** [comment]
I'm ready for a new release I do not plan other changes.

**Comment by ctron** [comment]
Ok then ...

**Comment by ctron** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by nfalco79** [comment]
there is a bug when run on nodes, the piece of code `Jenkins.getActiveInstance()` throws an IllegalStateException. It works only on master. This evening I will try to fix it, taking the proxy configuration in DroneRecorder and pass to the UploadFile MasterToSlaveCallable.

**Comment by nfalco79** [comment]
I Ran build until a slave node is taken and upload was success. Sorry for the bug.

**Comment by nfalco79** [comment]
Please release 0.5.1

**Comment by ctron** [comment]
No worries 😉 ... thanks for the quick fix!

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by ctron** [comment]
I might take a bit before the plugin is synced on the update server of Jenkins.
