### ISSUE TITLE
Support for using from Jenkinsfile

### ISSUE THREAD

**Issue by minemeraj** [ctron/package-drone-jenkins#28]
I want to use this plugin from Jenkinsfile. I don't know if it is possible right now.

**Comment by nfalco79** [comment]
this plugin supports pipeline. You can configure it using Pipeline Syntax menu item available in any Pipeline job

Example:
```
pdrone artifacts: '**/*.zip', channel: 'mavenChannel', credentialsId: 'mycredential', excludes: null, serverUrl: 'localhost', stripPath: true
```
